### ISSUE TITLE
AssertionError: detector file megadetector/md_v5a.0.0.pt does not exist

### ISSUE THREAD

**Issue by dvelasco3** [microsoft/CameraTraps#304]
I'm trying to run megadetector on an online linux based docker container with GPU access, but for some reason I am unable to open the "mdv5a.0.0.pt", despite me uploading it to my virtual GUI file explorer. Here's an example of what I'm running into.

Here's what I run: 
(cameratraps-detector) jovyan@a18fbc2ea:~/work/~git/cameratraps$ python detection/run_detector.py "megadetector/md_v5a.0.0.pt" --image_file "test1.jpg" --threshold 0.2

Here's what I get back:

Traceback (most recent call last):
  File "detection/run_detector.py", line 460, in <module>
    main()
  File "detection/run_detector.py", line 433, in main
    assert os.path.exists(args.detector_file), 'detector file {} does not exist'.format(args.detector_file)
AssertionError: detector file megadetector/md_v5a.0.0.pt does not exist
<img width="694" alt="Capture" src="https://user-images.githubusercontent.com/98203801/178891433-8262e940-f477-47c6-83b1-885f09543271.PNG">

**Comment by dvelasco3** [comment]
I was able to fix this by typing "md_v5a.0.0.pt" instead of megadetector/md_v5a.0.0.pt"
