### ISSUE TITLE
JSON List for batch processing

### ISSUE THREAD

**Issue by arpitdeomurari** [microsoft/CameraTraps#351]
Hi,

I'm trying to pass custom list of images (Not single image of directory of images) to run_detector_batch.py. But I'm getting various errors and none of the json format works.

JSON example:

`{
 "images": [
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141311_I__00010.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141316_I__00011.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141321_I__00012.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141326_I__00013.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141331_I__00014.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141336_I__00015.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141341_I__00016.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141346_I__00017.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141351_I__00018.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141405_I__00019.JPG"},
{"image_file": "/media/comp_operator/Organised_data/54B/20201223_141410_I__00020.JPG"}
]
}`

Error: 

`Loaded 1 image filenames from list file /media/comp_operator/Organised_data/54b.json
Traceback (most recent call last):
  File "/home/tallk/0CamAI_Species/0CamAI_PAVE.py", line 751, in <module>
    main()
  File "/home/tallk/0CamAI_Species/0CamAI_PAVE.py", line 680, in main
    assert os.path.exists(image_file_names[0]), 'The first image to be scored does not exist at {}'.format(image_file_names[0])
KeyError: 0`

Can someone help me in getting this done quickly.
Thanks in Advance....

**Comment by nomoneyExpection** [comment]
I have a new problem. After installing it according to its installation environment requirements, run python detection\run_detector.py "c:\megdetector\md_v5a.0.0.pt" --image_file "some_image_file.jpg " --threshold 0.1, the error ModuleNotFoundError: No module named 'md_visualization', do you have a solution?
